audit_header: false
title: Seattle Real Estate Video Blog with Vija Williams
description: Our mission at The Vija Group is to be your best resource for Seattle real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Vija Group, your professional Seattle Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Vija Williams
  title:
  license_number:
  about_markdown: |
    Vija Williams is based in Kirkland, Washington in the Seattle area. She heads an award winning team of real estate specialists in the greater Seattle area focusing on the move-up and luxury segments. The Vija Team is the #1 residential resale real estate group at the Keller Williams Eastside office, and is in the top 1% of Keller Williams worldwide for volume sold. Keller Williams Worldwide has over 100,000 agents.
  market: Seattle
  brand: The Vija Group
  brokerage: Keller Williams Realty
  address: '11109 Slater Ave NE, #200<BR>Kirkland, WA 9033'
  phone: 425-998-8452
  phone_type:
  phone2:
  phone2_type:
  email: vija@vijawilliams.com
  url: http://www.vijacentral.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.vijacentral.com/sell/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.vijacentral.com/results/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your Seattle Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.vijacentral.com/sell/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a Seattle Home?"
    CTA_text2: "Search the entire MLS for your Seattle home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.vijacentral.com/results/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/VijaTeam
  linkedin_url: http://www.linkedin.com/in/vijawilliams
  gplus_url:
  youtube_url:
  twitter_url: http://twitter.com/viavija
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/viavija/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Seattle Real Estate Podcast with Vija Williams'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Seattle Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Vija Group - your professional Seattle Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Seattle, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Vija Williams'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: Seattle Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#e51937'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
